### ISSUE TITLE
Problem to load plugin

### ISSUE THREAD

**Issue by zobi** [amlinger/homebridge-telldus-tdtool#5]
Hi, i've a problem to load your plugin :

```
[Sat Jul 09 2016 15:03:12 GMT+0200 (CEST)] Loaded plugin: homebridge-telldus
[Sat Jul 09 2016 15:03:12 GMT+0200 (CEST)] Registering platform 'homebridge-telldus.Telldus'
[Sat Jul 09 2016 15:03:12 GMT+0200 (CEST)] ---
[Sat Jul 09 2016 15:03:12 GMT+0200 (CEST)] Loaded plugin: homebridge-telldus-tdtool
[Sat Jul 09 2016 15:03:12 GMT+0200 (CEST)] Registering platform 'homebridge-telldus-tdtool.Telldus-TD-Tool'
[Sat Jul 09 2016 15:03:12 GMT+0200 (CEST)] ---
[Sat Jul 09 2016 15:03:12 GMT+0200 (CEST)] Loaded config.json with 1 accessories and 1 platforms.
[Sat Jul 09 2016 15:03:12 GMT+0200 (CEST)] ---
[Sat Jul 09 2016 15:03:12 GMT+0200 (CEST)] Loading 1 platforms...
[Sat Jul 09 2016 15:03:12 GMT+0200 (CEST)] [Telldus-TD-Tool] Initializing Telldus-TD-Tool platform...
[Sat Jul 09 2016 15:03:12 GMT+0200 (CEST)] [Telldus-TD-Tool] Loading devices...

/usr/lib/node_modules/homebridge-telldus-tdtool/dist/lib/tdtool.js:11
  return new Promise(function (resolve, reject) {
             ^
ReferenceError: Promise is not defined
    at execute (/usr/lib/node_modules/homebridge-telldus-tdtool/dist/lib/tdtool.js:11:14)
    at Object.isInstalled (/usr/lib/node_modules/homebridge-telldus-tdtool/dist/lib/tdtool.js:24:12)
    at Object.listDevices (/usr/lib/node_modules/homebridge-telldus-tdtool/dist/lib/tdtool.js:30:19)
    at TelldusTDToolPlatform.accessories (/usr/lib/node_modules/homebridge-telldus-tdtool/dist/index.js:30:14)
    at Server._loadPlatformAccessories (/usr/lib/node_modules/homebridge/lib/server.js:333:20)
    at Server._loadPlatforms (/usr/lib/node_modules/homebridge/lib/server.js:277:16)
    at Server.run (/usr/lib/node_modules/homebridge/lib/server.js:71:36)
    at module.exports (/usr/lib/node_modules/homebridge/lib/cli.js:40:10)
    at Object.<anonymous> (/usr/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:456:26)
```

Have you an idea to solve this ? 

Thanks a lot for your help
i'm on Debian Wheezy

**Comment by amlinger** [comment]
Hi zobi,

It sounds like you are using an old version of this package (which runs ES2015, but does not transpile it, as newer versions do), in combination with using an older node version that does not run ES2015.

Try upgrading the package and see if this solves your problem.

**Comment by zobi** [comment]
Great i upgrade my nodejs version and it works ;) 
Thanks a lot for your help
